### ISSUE TITLE
Updated add friend dialog

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#138]
GOT INVITED?
Tap the zom.im link you received to add your friend

zom.im should be zom primary color!

**Comment by n8fr8** [comment]
![screenshot_20160915-161101](https://cloud.githubusercontent.com/assets/30851/18565787/27fa0d68-7b5f-11e6-98b8-58dad68bf2ef.png)

**Comment by jodiejones** [comment]
ADD FRIENDS! (can you make this text the magenta Zom color)
keep icons but remove written instructions
(if possible please make icons larger)

GOT INVITED? (can you make this text the magenta Zom color)
change written instruction to: Tap the Zom invite link from your friend or scan their QR code now

Can we change ADVANCED to Add directly:
Written instruction: Enter your friend's full username (ie. zomisfun.4x3f5g@zom.org) here:

because of the flashing | the eye is still drawn to the advanced option - 
is it possible to not have the | but instead if users want to add someone directly they can tap on the line to enter text
(can the line be changed to the magenta Zom color)

**Comment by n8fr8** [comment]
This is an emulator view, but pretty close to what it will be 

![layout-2016-09-22-105459](https://cloud.githubusercontent.com/assets/30851/18753353/0d105292-80b3-11e6-9318-5995d79fe4af.png)
