### ISSUE TITLE
Inbox / Archive Toggle in Conversations View

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#229]
Inbox shows news chats with friends you’ve previously had chats with.
Archive shows pre-existing chats for the migrated account (ie the one you migrated from).

**Comment by n8fr8** [comment]
I am implementing the archive toggling / swiping in line with the Android Material/Gmail/Signal approach on this. Swipe will only be for "Archiving" and not for "Delete", since it is too easy to accidentally swipe and delete something. Displaying the archived conversations can be done by finding the old contact and tapping on them, which will bring up the archived chat. There is also an action bar "Archive" icon that you tap to toggle conversation and contact list to show the "Archived" view.

There is no equivalent inbox|archive toggle control, as we have it on iOS, and also with the controls at the top, and the action bar, it is too cluttered and awkward to simulate what we have on iOS.
