### ISSUE TITLE
Unable to archive friends

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#248]
Correct me if I'm wrong, but I can't seem to find a way to do this.

Suggestion:
I would disable swiping between the main views, so that we can fully leverage it in the individual views. If we did this, we could add the reveal for deleting and archiving chats and friends. This is nice because it matches what is happening on iOS, while still using an interaction that people expect to see on Android.

**Comment by n8fr8** [comment]
I have implemented swiping to archive in the contacts tab now. The archive action bar also now toggles the view.

Since tabs are no top you need swipe or else people have to reach up to the top everytime. This doesn't work for one handed use. So, we can move the tabs to the bottom and disable the swiping, or leave the swiping in.
