### ISSUE TITLE
No double check for messages sent to groups

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#278]

**Comment by chrisballinger** [comment]
Delivery receipts don't really make as much sense in a group context,
because you'll need to receive a receipt from every participant, and it's
not guaranteed that all clients in a group will send receipts.

**Comment by n8fr8** [comment]
Yet, both WhatsApp and Signal support them. I think having an indicator that at least one person received it is good enough for me, and then in the future, showing how many people or who saw it, would be excellent. 

From a user perspective, it feels like something is wrong, when I only see one check, since we have conditioned them to expect the double. 

Perhaps there is a middle ground? Successful delivery to the room should be an instant double check? One delivery receipt received a double check?

**Comment by cstiens** [comment]
> From a user perspective, it feels like something is wrong, when I only see one check, since we have conditioned them to expect the double.

Agreed. I think we should have a solution for this when we release the public build. 

> Perhaps there is a middle ground? Successful delivery to the room should be an instant double check? One delivery receipt received a double check?

I think something like this makes sense. Let's talk about it on Monday's scrum.
