### ISSUE TITLE
Pending Approval

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#295]
The scenario is — An Android friend adds me. I'm on iOS and accept the friend request. But, after accepting, the UI in the chat with them showing 'pending approval'. 

This issue is filed on iOS here: https://github.com/zom/Zom-iOS/issues/350

**Comment by N-Pex** [comment]
@n8fr8 I think I managed to track this down! =)

It happened to me today almost every time, so I could throw some debugging at it. The repro steps were:

(0. - When doing several retests: make sure that the corresponding users are not in list on iOS and/or Android, else delete them. They might pop up again, something we need to look at maybe?)
1. On iOS add the Android account. I did this just by typing in the full username under "advanced".
2. On Android, wait until the notification comes in, then tap the notification to open the chat view.
3. In the toast that pops up "Add Xyz?", hit "yes".

Result: on iOS the newly added user is still shown "Pending Approval".

I tracked this down to "entry" being null at line 3166 in XmppConnection.approveSubscriptionRequest. entry.canSeeMyPresence() will thus create an exception, resulting in that the "subscribed" presence stanza is actually never sent!

I think this is because createEntry (line 3162) is asynchronous, so the getEntry on the next line will almost always return null. Not sure how to fix, could you have a look?

**Comment by n8fr8** [comment]
Thanks for the digging. I guess we can loop and wait for a non-null entry to return?

**Comment by N-Pex** [comment]
I guess we should try this again now, after all changes made. Also zom/Zom-iOS#350.
